### ISSUE TITLE
Hackintosh 10.13.3 (17D47) use  webdriver.sh get error

### ISSUE THREAD

**Issue by CocoaHoo** [vulgo/webdriver.sh#4]
Operating System: macOS 10.13.3 (17D47)
Computer: iMac18,2
GPU: GeForce 1050ti
Version: 1.3.0
Disable SIP: 0x67

webdriver.sh: line 44: syntax error near unexpected token `('

webdriver.sh: line 44: `$grep -qiE -e "status: disabled|signing: disabled" <(/usr/bin/csrutil status) && KEXT_ALLOWED=true'

**Comment by vulgo** [comment]
How are you calling the script? It's not ``` sudo sh ./webdriver.sh ``` by any chance?

**Comment by CocoaHoo** [comment]
I use the old version to solve this problem

**Comment by vulgo** [comment]
No worries. This appears to be caused by not using bash or invoking bash with ```sh``` triggering POSIX mode. shellcheck tells us
```
$grep -qiE -e "status: disabled|signing: disabled" <(/usr/bin/csrutil status) && KEXT_ALLOWED=true
                                                   ^-- SC2039: In POSIX sh, process substitution is undefined.
```
Calling the script normally with bash>3.2 there is no syntax error.

[https://www.gnu.org/software/bash/manual/html_node/Bash-POSIX-Mode.html](https://www.gnu.org/software/bash/manual/html_node/Bash-POSIX-Mode.html)
